name: Actions main (Scheduled)

on:
  push:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip' #dependency caching
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-api.txt
        
    - name: Run Daily Batch
      run: |
        python ./files/src/dashboard/daily_batch.py #メインスクリプトを実行
        git add .
        git commit -m "crongenerated"
        git push
      env:
        OPENAI_API: ${{ secrets.OPENAI_API }}
