name: Deploy to Gh-pages (Scheduled)

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-api.txt
    - name: Run script
      run: |
        python ./files/src/dashboard/forecast.py #メインスクリプトを実行

    - name: Run marketgenerate script
      run: |
        python ./files/src/dashboard/generatehtml.py #メインスクリプトを実行
      env:
        TEST: ${{ secrets. }}

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
